---
# TODO: Write a script to launch Minikube and then execute
- name: Self-configuration of Ansible server
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Set right permissions to private key
      ansible.builtin.file:
        path: /home/ansible/dbkey.pem
        mode: '0400'
        group: ansible
        owner: ansible

    - name: Set AWX
      become: true
      block:
        - name: Install necessary packages for Docker Engine
          ansible.builtin.apt:
            update_cache: true
            state: latest
            name:
              - ca-certificates
              - gnupg
              - lsb-release

        - name: Download GPG key from Docker
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /tmp/docker.gpg
        
        - name: Dearmor downloaded key and write it to keyring directory
          ansible.builtin.expect:
            command: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
            responses:
              (?i)overwrite: "y"

        - name: Check architecture
          ansible.builtin.command: 
            cmd: dpkg --print-architecture
          register: arch

        - name: Check Ubuntu version codename
          ansible.builtin.command: 
            cmd: lsb_release -cs
          register: lsb
          
        - name: Add Docker source list to Aptitude sources.list.d directory
          ansible.builtin.copy: 
            content: "deb [arch={{ arch.stdout }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ lsb.stdout }} stable"
            dest: /etc/apt/sources.list.d/docker.list

        - name: Install Docker
          ansible.builtin.apt:
            update_cache: true
            state: latest
            name:
              - docker-ce 
              - docker-ce-cli 
              - containerd.io 
              - docker-compose-plugin

        - name: Add Ansible user to Docker group
          ansible.builtin.command:
            cmd: usermod -aG docker ansible
              
        - name: Check if Minikube is available on the system
          ansible.builtin.command:
            cmd: which minikube
          register: minikube
          ignore_errors: true

        - name: Download and install Minikube from Google servers
          ansible.builtin.apt:
            deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
          when: minikube.rc != 0

 
    # - name: Run Kubernetes cluster in Minikube 
    #   ansible.builtin.shell:
    #     cmd: newgrp docker && minikube start --addons=ingress --cpus=4 --cni=flannel --install-addons=true --kubernetes-version=stable --memory=4g
    
