---
- name: Playbook for common tasks for every host in inventory to keep stuff DRY
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Change hostname to Inventory hostname
      ansible.builtin.hostname: 
        name: "{{ inventory_hostname }}"
      register: hostname

    - name: Change /etc/hosts
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '\bnotnamed\b'
        replace: '{{ inventory_hostname }}'
      register: hosts


