---
- name: Playbook gathering all the other playbooks to provision infra
  hosts: localhost
  gather_facts: yes

- name: Provision Ansible server
  ansible.builtin.import_playbook: "{{ playbook_dir }}/ansible-playbook.yaml"

- name: Common provisioning for every host to keep stuff DRY
  ansible.builtin.import_playbook: "{{ playbook_dir }}/common-playbook.yaml"

- name: Provision Gitea server
  ansible.builtin.import_playbook: "{{ playbook_dir }}/gitea-playbook.yaml"

- name: Provision PostgreSQL server nodes
  ansible.builtin.import_playbook: "{{ playbook_dir }}/postgresql-playbook.yaml"

- name: Provision PGPool load balancer
  ansible.builtin.import_playbook: "{{ playbook_dir }}/pgpool-playbook.yaml"