---
- name: Installation and configuration Kubernetes infrastructure
  hosts: kubernetes
  gather_facts: true

  tasks: 
    - name: Disable swap on every machine
      ansible.builtin.shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab && swapoff -a
      become: true
