---
# TODO:
# Add hardcoded backend_data_directory to variable and send to Jinja2 script

- name: Configuration of PGPool server
  hosts: pgpool
  gather_facts: yes
  become: true

  tasks:
    - name: Install PGPool package and other tools
      ansible.builtin.apt:
        update_cache: true 
        state: latest
        name: 
          - pgpool2
          - postgresql-client-14
          - net-tools

    - name: Stop PGPool service
      ansible.builtin.systemd:
        name: pgpool2
        enabled: true
        state: stopped
   
    - name: Delete old config file
      ansible.builtin.file:
        path: "/etc/pgpool2/{{ item.conf }}"
        state: absent
      loop:
        - { conf: pgpool.conf }
        - { conf: pool_hba.conf }

    - name: Generate config file from template
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/{{ item.src }}"
        dest: "/etc/pgpool2/{{ item.dest }}"
      loop:
        - { src: pgpool.j2, dest: pgpool.conf }
        - { src: pool_hba.j2, dest: pool_hba.conf }
    
    - name: Remove node status file
      ansible.builtin.file: 
        state: absent
        path: /var/log/postgresql/pgpool_status

    - name: Start PGPool service
      ansible.builtin.systemd:
        name: pgpool2
        enabled: true
        state: started


    